name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: echo "easyscan.url=${{ secrets.EASYSCAN_URL }}" > local.properties

    - name: Build debug APK
      run: ./gradlew :composeApp:assembleDebug

    - name: Build release APK
      run: ./gradlew :composeApp:assembleRelease

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: easyscan-debug-apk
        path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: easyscan-release-apk
        path: composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK and upload
      id: sign_app
      with:
        releaseDirectory: composeApp/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
